### ISSUE TITLE
 fatal error: wiringPi.h: No such file or directory

### ISSUE THREAD

**Issue by ManojMMWWIndia** [marcandreuf/sunfounder-sensors-raspi-4j#1]
/sunfounder-sensors-raspi-4j$ cd /media/neosoft/65bdfc40-d156-4da8-a774-3cc0b8d9ed94/IOT_projects/sunfounder-sensors-raspi-4j/src/main/java
neosoft@IT06-97:/media/neosoft/65bdfc40-d156-4da8-a774-3cc0b8d9ed94/IOT_projects/sunfounder-sensors-raspi-4j/src/main/java$ sudo sh jniDHT11SensorReaderBuilder.sh 
Compile java class org/mandfer/dht11/DHT11SensorReader.java
Create JNI header file DHT11SensorReader.h
Simplify header class name to org/mandfer/dht11/DHT11SensorReader.h
Compile org/mandfer/dht11/dht11sensor.c with wiringPi library
org/mandfer/dht11/dht11sensor.c:15:22: fatal error: wiringPi.h: No such file or directory
 #include <wiringPi.h>
                      ^
compilation terminated.
Copy new org/mandfer/dht11/dht11sensor.so in /usr/lib/
cp: cannot stat ‘org/mandfer/dht11/dht11sensor.so’: No such file or directory
Create symbolic link for the library2
Updated library:
lrwxrwxrwx 1 root root 23 Jun  8 17:42 /usr/lib/libdht11sensor.so -> /usr/lib/dht11sensor.so

**Comment by marcandreuf** [comment]
Looks like you do not have the Wiringpi lib installed. 
You can check [here](http://pi4j.com/install.html#Installation)
